##############################################################
# EasyServerManager                                          #
# Created by MysticalShadow95                                #
# Support on Discord http://discord.aniheaven.net/           #
# All right reserved by MysticalShadow95                     #
# Minecraft version tested on 1.21.3                         #
##############################################################
#                       Setting Plugin                       #
#                  SaveType: [file or sql]!                  #
#                      Setting Messages                      #
##############################################################
EasyServerManager:
  Prefix: "&8&l[&3&lEasy&b&lServer&3&lManager&8&l] &8"
  AllowJoinMessage: true
  AllowQuitMessage: true
  AllowPlayTeleportSound: true
  Farminworld: "farmwelt"
  MaxPlayers: 10
  SaveType: "file"
  ServerName: "SiedlerMC"
  MaxSaveLevel: 2500
####################################################################
#                        Setting Messages                          #
#  Alias "%player%" define the Player on the Join or Quit message  #
#     Alias "%player%" define the Player on the PlayerMessages     #
#      Alias "%warp%" define the Player on the warp commands       #
#         Alias "%home%" define the homes from a Player            #
#               Alias "%jail%" define the jailname                 #
#            Alias "%reason%" define the Kick reasons              #
#   In the path UseCommandMSG Nothing may be entered after the /   #
####################################################################
Messages:
  JoinMessage: "&8[&a+&8] %player%"
  QuitMessage: "&8[&4-&8] %player%"
  MOTDHeader: "&3&lServerName &2&l| §aSecond Message"
  MOTDFooter: "&4&lNEWS: &c&lIngame Voice &2&l| &c&lNew BanSystem"
  MOTDMaintenance: "&4The server is currently undergoing maintenance work"
  SetWarpMSG: "&2You successfully set the Warp &2%warp%"
  RemoveWarpMSG: "&4You successfully removed the Warp &c%warp%"
  WarpAlreadyExistMSG: "&4The warp &c%warp% &4already exist!"
  WarpDoesNotExistMSG: "&4The warp &c%warp% &4does not exist!"
  UseCommandMSG: "&bUse command &8/"
  TeleportToWarpMSG: "&2You teleport successfully teleport to the Warp §3%warp% &2!"
  OnlyRealPlayer: "&4This command cannot be used"
  TeleportToDeathMSG: "&2You successfully teleport to your death point!"
  DeathNotFoundMSG: "&4does not found your last Death point!"
  SuccessfullyChatClearedMSG: "&2The chat Successfully Cleared"
  AllChatClearMSG: "&2The chat cleared by &3%player%"
  PlayerNotExist: "&4Player does not exist!"
  AnotherPlayerClearMSG: "&2The player &3%player% &2has clear your Inventory!"
  PlayerClearMSG: "&2The Inventory from the player §3%player% &2successfully cleared!"
  DepositSuccessfullyMSG: "&2The deposit was successfully!"
  EnoughLevelMSG: "&4You don't have enough level!"
  ReachMaxLevelMSG: "&4You reached the Maximum save Level!"
  OpenEnderchestMSG: "&2Your open the enderchest from the player!"
  OpenYourselfEnderchestMSG: "&4You cannot open your enderchest!"
  TeleportToFarmMSG: "&2You successfully teleport to the Farmworld"
  CannotFindFarmworldMSG: "&4Cannot find the farmworld. &cPlease contact the server Administration"
  DeactivatedFlyMSG: "&4You cannot flying"
  ActivatedFlyMSG: "&2You can now flying"
  ActivatedFlyByPlayerMSG: "&2You activated the flying mode on the player &3%player%"
  ActivatedFlyFromMSG: "&2The player &3%player% &2has activated your fly mode!"
  DeactivatedFlyByPlayerMSG: "&2You deactivated the flying mode on the player &3%player%"
  DeactivatedFlyFromMSG: "&4The player &c%player% &4has deactivated your fly mode!"
  GameModeSurvivalSelfMSG: "&2You are now in survival mode!"
  GameModeCreativeSelfMSG: "&2You are now in creative mode!"
  GameModeAdventureSelfMSG: "&2You are now in adventure mode!"
  GameModeSpectatorSelfMSG: "&2You are now in spectator mode!"
  GameModeAlreadyInSurvivalSelfMSG: "&4You are already on an survival mode!"
  GameModeAlreadyInCreativeSelfMSG: "&4You are already on an creative mode!"
  GameModeAlreadyInAdventureSelfMSG: "&4You are already on an adventure mode!"
  GameModeAlreadyInSpectatorSelfMSG: "&4You are already on an spectator mode!"
  GameModeSurvivalAnnotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Survival-Mode"
  GameModeCreativeAnnotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Creative-Mode"
  GameModeAdventureAnnotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Adventure-Mode"
  GameModeSpectatorAnntotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Spectator-Mode"
  GameModeAlreadyInSurvivalAnnotherPlayerMSG: "&4You are already on an survival mode!"
  GameModeAlreadyInCreativeAnnotherMSG: "&4You are already on an creative mode!"
  YourHealedMSG: "&2You successfully healed!"
  YouTeleportToYourHomeMSG: "&2You successfully teleport to your Home &3%home%&2!"
  HomeNotExistMSG: "&4The home &c%home% &4does not exist!"
  HomeSetMSG: "&2The home &3%home% &2was set!"
  HomeRemovedMSG: "&2The home &3%home% &2successfully deleted!"
  HomeAlreadyExistMSG: "&4The home &c%home% &4is already exist!"
  YourJailedHomeMSG: "&4You jailed. You cannot teleport to your Home &c%home%&4!"
  YourHealedAnnotherPlayerMSG: "&2You healed the Player &3%player%&2!"
  YourHealedFromPlayerMSG: "&2You healed from &3&2%player%&2!"
  YourJailedFromPlayerMSG: "&2You healed from &3%player%&2!"
  YourJailedPlayerMSG: "&2You healed from &3%player%&2!"
  GameModeAlreadyInAdventureAnnotherPlayerMSG: "&4You are already on an adventure mode!"
  GameModeAlreadyInSpectatorAnnotherPlayerMSG: "&4You are already on an spectator mode!"
  GameModeSetInSurvivalAnnotherPlayerMSG: "&2You set the player &3%player% &2to Survival-Mode!"
  GameModeSetInCreativeAnnotherPlayerMSG: "&2You set the player &3%player% &2to Creative-Mode!"
  GameModeSetInAdventureAnnotherPlayerMSG: "&2You set the player &3%player% &2to Adventure-Mode!"
  GameModeSetInSpectatorAnnotherPlayerMSG: "&2You set the player &3%player% &2to Spectator-Mode!"
  GameModeAlreadyPlayerInSurvivalMSG: "&4The player &c%player% &4is already in Survival-Mode!"
  GameModeAlreadyPlayerInCreativeMSG: "&4The player &c%player% &4is already in Creative-Mode!"
  GameModeAlreadyPlayerInAdventureMSG: "&4The player &c%player% &4is already in Adventure-Mode!"
  GameModeAlreadyPlayerInSpectatorMSG: "&4The player &c%player% &4is already in Spectator-Mode!"
  ActivatedYourGodModeMSG: "&2You are now in God mode!"
  DeactivatedYourGodModeMSG: "&4You are no longer in God mode!"
  YouActivatedGodAnnotherPlayerMSG: "&2The player &3%player% &2is now in God-Mode"
  YouDeactivatedGodAnnotherPlayerMSG: "&4The player &c%player% &4is no longer in God-Mode!"
  YouActivatedGodFromPlayerMSG: "&2The player &3%player% &2set you in God-Mode!"
  YouDeactivatedGodFromPlayerMSG: "&4The player &c%player% &4removed your God-Mode!"
  InvseeMSG: "&2You can now see the player's inventory!"
  InvseeYourselfMSG: "&4Why do open yourself inventory!"
  YouJailedAPlayerMSG: "&2You successfully jailed the player &3%player%&2!"
  YouJailedFromPlayer: "§4You was jailed from the player &c%player%&4!"
  PlayerAlreadyJailedMSG: "&4The player &c%player% &4already jailed!"
  PlayerIsNotJailedMSG: "&4The player &c%player% &4is not Jailed!"
  JailNotExistMSG: "&4The jail &c%jail% &4does not exist!"
  PlayerUnjailedFromMSG: "&2You successfully unjailed the player &3%player%&2!"
  PlayerUnjailedMSG: "&2You where from &3%player% &2dismissed!"
  WarpSpawnNotFoundMSG: "&4Cannot find the spawn. &cPlease contact the server Administration"
  ThePathNotFoundMSG: "&4The path does not exist!"
  UnjailedYourselfMSG: "&4You cannot unjailed yourself!"
  KickMSG: "\n\n&bDu wurdest vom Server gekickt!\n&cGrund: &4%reason%"
  KickPlayerMSG: "&8gekickt wurdest du von: §7%player%"
  KickYourselfMSG: "&4Why do you kick yourself?!"
  SuccessfullyKickPlayerMSG: "&2You successfully kicked the player &3%player% &2from the Server!"
  AddedPlayerLevelMSG: "&2Successfully given the player &3%player% &2the specified level!"
  AddedLevelFromPlayerMSG: "&2You become from the player &3%player% &2Level!"
  RemovedPlayerLevelMSG: "&2Successfully removed the player &3%player% &2the specified level!"
  RemovedLevelFromPlayerMSG: "&4Removed level from the player &c%player%&4!"
  EnoughPlayerLevel: "&4The player &c%player% &4has not enough level!"
  AnnotherPlayerExistNotAFileMSG: "&4The player &c%player% &4has not exist a File!"
  AnnotherPlayerHaveNoHomesMSG: "&4The player &c%player% &4has not any Homes!"
  AnnotherPlayerHomes: "&2The Homes from the Player &3%player% &2Homes: "
  YourHomesMSG: "&2Your Homes: &3"
  YourHaveNoHomesMSG: "&4You don't have any homes!"
  KickPlayerWhenActivateMaintenanceMSG: "&3ServerName\n&aYou was kicked from the server!\n\n&4REASON: &cMaintenance Works\n&3been kicked by: &4System"
  ActivateMaintenanceModeMSG: "&2You successfully activated the maintenance mode!"
  DeactivateMaintenanceModeMSG: "&4You successfully deactivated the maintenance mode!"
  PayedLevelMSG: "&2You have successfully transferred the specified amount to the player!"
  PayedLevelAnnotherPlayerMSG: "&2You become from the player &3%player% &2Level!"
  PayoutSuccessfullyMSG: "&2The payout was successfully!"
  AnnotherPlayerPingMSG: "&2The specified player has a ping of &3"
  PingYourselfMSG: "&2You have a ping from &3"
  PingInMSMSG: "&2ms!"
  ActivatedYourselfPvPMSG: "&2You activated your PVP status!"
  AlreadyActivatedYourselfPvPMSG: "&2You activated your PVP status!"
  DeactivatedYourselfPvPMSG: "&4You deactivated your PVP status!"
  AlreadyDeactivatedYourselfPvPMSG: "&4You already deactivated the PvP!"
  YouGotRewardMSG: "&2got today's reward!"
  GotPlayerRewardNotify: "&2The player &3%player% &2Collected his reward!"
  AlreadyPickupRewardMSG: "&4you already picked up your reward today!"
  SetJailMSG: "&2You successfully created the Jail!"
  TeleportToSpawnMSG: "&2You successfully teleport to the Spawn!"
  TeleportToThePlayerMSG: "&2You teleport to the player &3%player%&2!"
  TeleportYourselfMSG: "&4You cannot to teleport yourself!"
  SuccessSetDayMSG: "&2You have successfully set the time to day!"
  SuccessSetNightMSG: "&2You have successfully set the time to night!"
  SuccessSetMidnightMSG: "&2You have successfully set the time to midnight!"
  YouDontTPARequestMSG: "&4You don't have a tpa request"
  DenyTPAMSG: "&2You successfully denied a tpa request!"
  AcceptTPAMSG: "&2You successfully accept a tpa request!"
  PlayerAcceptTPAMSG: "&2The player &3%player% &2successfully teleported to you!"
  PlayerDeniedTPAMSG: "&4The player &c%player% &4denied your tpa request!"
  SendPlayerTPAMSG: "&2You successfully send a tpa request. To the player &2%player%&2!"
  ReceivedRequestMSG: "&2You have a tpa request from &3%player%&2!"
  AcceptRequestMSG: "&2Accept: /tpa accept &3%player%&2!"
  DeniedRequestMSG: "&2Deny: /tpa deny &3%player%&2!"
  TpherePlayerMSG: "&2You have successfully teleported the player &3%%player &2to you!"
  WeatherChangedSunMSG: "&2The weather change to sun!"
  WeatherChangedRainMSG: "&The weather change to rain!"
  WeatherChangedThunderMSG: "&2The weather change to thunder!"
  CurrentlyJailed: "&4You are currently Jailed!"
  PlayerKilledByPlayerMSG: "&8The player &3%player% &8has killed by &3%killer%&8!"
  PlayerDeathMSG: "&8The player &3%player% &8is died!"
##############################################################
#                  Setting the Rank Prefix                   #
##############################################################
Rank:
  Owner: "&8[&4Owner&8] %player% &7» "
  CoOwner: "&8[&4Co-Owner&8] %player% &7» "
  SrAdmin: "&8[&cSrAdmin&8] %player% &7» "
  Admin: "&8[&cAdmin&8] %player% &7» "
  SrDeveloper: "&8[&bSrDeveloper&8] %player% &7» "
  Developer: "&8[&bDeveloper&8] %player% &7» "
  TestDeveloper: "&8[&bT-Developer&8] %player% &7» "
  SrModerator: "&8[&2SrModerator&8] %player% &7» "
  Moderator: "&8[&2Moderator&8] %player% &7» "
  TestModerator: "&8[&2T-Moderator&8] %player% &7» "
  SrSupporter: "&8[&3SrSupporter&8] %player% &7» "
  Supporter: "&8[&3Supporter&8] %player% &7» "
  TestSupporter: "&8[&3T-Supporter&8] %player% &7» "
  SrBuilder: "&8[&9SrBuilder&8] %player% &7» "
  Builder: "&8[&9Builder&8] %player% &7» "
  TestBuilder: "&8[&9T-Builder&8] %player% &7» "
  Friend: "&d%player% &7» "
  YouTuber: "&5%player% &7» "
  Streamer: "&5%player% &7» "
  PremiumThree: "&6%player% &7» "
  PremiumTwo: "&6%player% &7» "
  PremiumOne: "&6%player% &7» "
  Player: "&8%player% &7» "
##############################################################
#                  Setting the RewardItems                   #
##############################################################
Reward:
  One:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Two:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Three:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Four:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Five:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Six:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Seven:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Eight:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Nine:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Ten:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Eleven:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Twelve:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Thirteen:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Fourteen:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Fifteen:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Sixteen:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Seventeen:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Eighteen:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
  Nineteen:
    Item: "NETHERITE_BLOCK"
    Name: "Test"
    Amount: 50
##############################################################
#                   Setting the JoinTitle                    #
##############################################################
Title:
  Header: "&3&lWelcome on the"
  Footer: "&2&lServer: &4&lServerName or Network Name!"
##############################################################
#                   Setting the TabList                      #
#         %date% set the current date. In TabHeader          #
#            With "\n" can you create a new Line             #
##############################################################
TabList:
  Header: "&3Willkommen auf \n&3ServerName\n\n&3Datum &2%date%\n\n&4&l----------------------------------\n"
  Footer: "\n&4&l----------------------------------\n\n&3Unser Discord: &2Link \n&3Live-Map &2Link"
##############################################################
#              Setting the Database connection               #
##############################################################
MySQL:
  Username: "root"
  Password: "press_here_youre_password"
  Host: "localhost"
  Datenbank: "servermanager"
  Port: 3306
##############################################################
#                 Setting the Permissions                    #
##############################################################
Perms:
  NoPermMSG: "&4You don't have permission to use this command!"
  PermSternchen: "easyservermanager.*"
  PermSetWarp: "easyservermanager.warp.set"
  PermRemoveWarp: "easyservermanager.warp.remove"
  PermHeal: "easyservermanager.heal"
  PermTPWarp: "easyservermanager.warp.tp"
  PermListWarp: "easyservermanager.warp.list"
  PermChatClear: "easyservermanager.chatclear"
  PermAllChatClearMSG: "easyservermanager.chatclear"
  PermClear: "easyservermanager.clear"
  PermEnderchest: "easyservermanager.enderchest"
  PermFly: "easyservermanager.fly"
  PermAnnotherFly: "easyservermanager.fly.other"
  PermGameMode: "easyservermanager.gamemode"
  PermGameModeAnnotherPlayer: "easyservermanager.gamemode.other"
  PermGodModeAnnotherPlayer: "easyservermanager.god.other"
  PermGodMode: "easyservermanager.god"
  PermInvsee: "easyservermanager.invsee"
  PermJail: "easyservermanager.jail"
  PermHealAnnotherPlayer: "easyservermanager.heal.other"
  PermKick: "easyservermanager.kick"
  PermLevel: "easyservermanager.level"
  PermGetOtherHomes: "easyservermanager.gethomes.other"
  PermMaintenanceJoin: "easyservermanager.maintenance.join"
  PermMaintenanceActivate: "easyservermanager.maintenance.activate"
  PermAnnotherPing: "easyservermanager.ping"
  PermRewardNotify: "easyservermanager.notify"
  PermSetJail: "easyservermanager.setjail"
  PermTeleport: "easyservermanager.teleport"
  PermTime: "easyservermanager.time"
  PermTPHERE: "easyservermanager.time"
  PermWeather: "easyservermanager.weather"
  PermSeePlugins: "easyservermanager.plugins"
  PermOwnerPrefix: "prefix.owner"
  PermCoOwnerPrefix: "prefix.coowner"
  PermSrAdminPrefix: "prefix.sradmin"
  PermAdminPrefix: "prefix.admin"
  PermSrDeveloperPrefix: "prefix.srdeveloper"
  PermDeveloperPrefix: "prefix.developer"
  PermTestDeveloperPrefix: "prefix.testdeveloper"
  PermSrModeratorPrefix: "prefix.srmod"
  PermModeratorPrefix: "prefix.mod"
  PermTestModeratorPrefix: "prefix.testmoderator"
  PermSrSupporterPrefix: "prefix.srsupporter"
  PermSupporterPrefix: "prefix.supporter"
  PermTestSupporterPrefix: "prefix.testsupporter"
  PermSrBuilderPrefix: "prefix.srbuilder"
  PermBuilderPrefix: "prefix.builder"
  PermTestBuilderPrefix: "prefix.testbuilder"
  PermFriendPrefix: "prefix.friend"
  PermYouTuberPrefix: "prefix.premiumthree"
  PermStreamerPrefix: "prefix.premiumtwo"
  PermPremiumThreePrefix: "prefix.premiumone"
  PermPremiumTwoPrefix: "prefix.youtuber"
  PermPremiumOnePrefix: "prefix.streamer"