##############################################################
# EasyServerManager                                          #
# Created by MysticalShadow95                                #
# Support on Discord http://discord.aniheaven.net/           #
# All right reserved by MysticalShadow95                     #
# Minecraft version tested on 1.21.3                         #
##############################################################
#                       Setting Plugin                       #
#                  SaveType: [file or sql]!                  #
#                      Setting Messages                      #
##############################################################
EasyServerManager:
  Prefix: "&8&l[&3&lEasy&b&lSiedler&3&lManager&8&l] &8"
  AllowJoinMessage: true
  AllowQuitMessage: true
  AllowPlayTeleportSound: true
  Farminworld: "farmwelt"
  MaxPlayers: 10
  SaveType: "file"
  ServerName: "SiedlerMC"
  MaxSaveLevel: 2500
####################################################################
#                        Setting Messages                          #
#  Alias "%player%" define the Player on the Join or Quit message  #
#     Alias "%player%" define the Player on the PlayerMessages     #
#      Alias "%warp%" define the Player on the warp commands       #
#         Alias "%home%" define the homes from a Player            #
#   In the path UseCommandMSG Nothing may be entered after the /   #
####################################################################
Messages:
  JoinMessage: "&8[&a+&8] %player%"
  QuitMessage: "&8[&4-&8] %player%"
  MOTDHeader: "&3&lSiedlerMC &2&l| §aDeutschsprachiges Projekt"
  MOTDFooter: "&4&lNEWS: &c&lIngame Voice &2&l| &c&lNew BanSystem"
  MOTDMaintenance: "&4The server is currently undergoing maintenance work"
  SetWarpMSG: "&3You successfully set the Warp &2%warp%"
  RemoveWarpMSG: "&4You successfully removed the Warp &c%warp%"
  WarpAlreadyExistMSG: "&4The warp &c%warp% &4already exist!"
  WarpDoesNotExistMSG: "&4The warp &c%warp% &4already exist!"
  UseCommandMSG: "&bUse command &8/"
  TeleportToWarpMSG: "&3You teleport successfully teleport to the Warp §2%warp% &3!"
  OnlyRealPlayer: "&4Error: &cThis command cannot be used"
  TeleportToDeathMSG: "&3You successfully teleport to your death point!"
  DeathNotFoundMSG: "&4does not found your last Death point!"
  SuccessfullyChatClearedMSG: "&3The chat Successfully Cleared"
  AllChatClearMSG: "&3The chat cleared by: &2%player%"
  PlayerNotExist: "&cPlayer does not exist!"
  AnotherPlayerClearMSG: "&3The player &2%player% &3has clear your Inventory!"
  PlayerClearMSG: "&3The Inventory from the player §2%player% &3successfully cleared!"
  DepositSuccessfullyMSG: "&3The deposit was successfully!"
  EnoughLevelMSG: "&cYou don't have enough level!"
  ReachMaxLevelMSG: "&4You reached the Maximum save Level!"
  OpenEnderchestMSG: "&3Your open the enderchest from the player!"
  OpenYourselfEnderchestMSG: "&cYou cannot open your enderchest!"
  TeleportToFarmMSG: "&3You successfully teleport to the Farmworld"
  CannotFindFarmworldMSG: "&4Cannot find the farmworld. &cPlease contact the server Administration"
  DeactivatedFlyMSG: "&cYou cannot flying"
  ActivatedFlyMSG: "&3You can now flying"
  ActivatedFlyByPlayerMSG: "&3You activated the flying mode on the player &2%player%"
  ActivatedFlyFromMSG: "&3The player &2%player% &3has activated your fly mode!"
  DeactivatedFlyByPlayerMSG: "&3You deactivated the flying mode on the player &2%player%"
  DeactivatedFlyFromMSG: "&4The player &c%player% &4has deactivated your fly mode!"
  GameModeSurvivalSelfMSG: "&2You are now in survival mode!"
  GameModeCreativeSelfMSG: "&2You are now in creative mode!"
  GameModeAdventureSelfMSG: "&2You are now in adventure mode!"
  GameModeSpectatorSelfMSG: "&2You are now in spectator mode!"
  GameModeAlreadyInSurvivalSelfMSG: "&4You are already on an survival mode!"
  GameModeAlreadyInCreativeSelfMSG: "&4You are already on an creative mode!"
  GameModeAlreadyInAdventureSelfMSG: "&4You are already on an adventure mode!"
  GameModeAlreadyInSpectatorSelfMSG: "&4You are already on an spectator mode!"
  GameModeSurvivalAnnotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Survival-Mode"
  GameModeCreativeAnnotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Creative-Mode"
  GameModeAdventureAnnotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Adventure-Mode"
  GameModeSpectatorAnntotherPlayerMSG: "&2The player &3%player% &2changed your gamemode to Spectator-Mode"
  GameModeAlreadyInSurvivalAnnotherPlayerMSG: "&4You are already on an survival mode!"
  GameModeAlreadyInCreativeAnnotherMSG: "&4You are already on an creative mode!"
  YourHealedMSG: "&3You successfully healed!"
  YouTeleportToYourHomeMSG: "&3You successfully teleport to your Home &2%home%&3!"
  HomeNotExistMSG: "&4The home &c%home% &4does not exist!"
  HomeSetMSG: "&3The home &2%home% &3was set!"
  HomeRemovedMSG: "&3The home &2%home% &3successfully deleted!"
  HomeAlreadyExistMSG: "&4The home &c%home% &4is already exist!"
  YourJailedHomeMSG: "&4You jailed. You cannot teleport to your Home &c%home%&4!"
  YourHealedAnnotherPlayerMSG: "&3You healed the Player &2%player%&3!"
  YourHealedFromPlayerMSG: "&3You healed from &2&2%player%&3!"
  YourJailedFromPlayerMSG: "&3You healed from &2&2%player%&3!"
  YourJailedPlayerMSG: "&3You healed from &2&2%player%&3!"
  GameModeAlreadyInAdventureAnnotherPlayerMSG: "&4You are already on an adventure mode!"
  GameModeAlreadyInSpectatorAnnotherPlayerMSG: "&4You are already on an spectator mode!"
  GameModeSetInSurvivalAnnotherPlayerMSG: "&2You set the player &3%player% &2to Survival-Mode!"
  GameModeSetInCreativeAnnotherPlayerMSG: "&2You set the player &3%player% &2to Creative-Mode!"
  GameModeSetInAdventureAnnotherPlayerMSG: "&2You set the player &3%player% &2to Adventure-Mode!"
  GameModeSetInSpectatorAnnotherPlayerMSG: "&2You set the player &3%player% &2to Spectator-Mode!"
  GameModeAlreadyPlayerInSurvivalMSG: "&4The player &c%player% &4is already in Survival-Mode!"
  GameModeAlreadyPlayerInCreativeMSG: "&4The player &c%player% &4is already in Creative-Mode!"
  GameModeAlreadyPlayerInAdventureMSG: "&4The player &c%player% &4is already in Adventure-Mode!"
  GameModeAlreadyPlayerInSpectatorMSG: "&4The player &c%player% &4is already in Spectator-Mode!"
  ActivatedYourGodModeMSG: "&3You are now in God mode!"
  DeactivatedYourGodModeMSG: "&3You are no longer in God mode!"
  YouActivatedGodAnnotherPlayerMSG: "&3The player &2%player% &3is now in God-Mode"
  YouDeactivatedGodAnnotherPlayerMSG: "&4The player &c%player% &4is no longer in God-Mode!"
  YouActivatedGodFromPlayerMSG: "&3The player &2%player% set you in God-Mode!"
  YouDeactivatedGodFromPlayerMSG: "&4The player &c%player% &4removed your God-Mode!"
  InvseeMSG: "&3You can now see the player's inventory!"
  InvseeYourselfMSG: "&4Why do open yourself inventory!"
##############################################################
#                   Setting to JoinTitle                     #
##############################################################
Title:
  Header: "&3&lWelcome on the"
  Footer: "&2&lServer: &4&lServerName or Network Name!"
##############################################################
#                    Setting to TabList                      #
#         %date% set the current date. In TabHeader          #
#            With "\n" can you create a new Line             #
##############################################################
TabList:
  Header: "&3Willkommen auf \n&3ServerName\n\n&3Datum &2%date%\n\n&4&l----------------------------------\n"
  Footer: "\n&4&l----------------------------------\n\n&3Unser Discord: &2Link \n&3Live-Map &2Link"
##############################################################
#              Setting to Database connection                #
##############################################################
MySQL:
  Username: "root"
  Password: "press_here_youre_password"
  Host: "localhost"
  Datenbank: "servermanager"
  Port: 3306
##############################################################
#                 Setting the Permissions                    #
##############################################################
Perms:
  NoPermMSG: "&4You don't have permission to use this command!"
  PermSternchen: "easyservermanager.*"
  PermSetWarp: "easyservermanager.warp.set"
  PermRemoveWarp: "easyservermanager.warp.remove"
  PermHeal: "easyservermanager.heal"
  PermTPWarp: "easyservermanager.warp.tp"
  PermListWarp: "easyservermanager.warp.list"
  PermChatClear: "easyservermanager.chatclear"
  PermAllChatClearMSG: "easyservermanager.chatclear"
  PermClear: "easyservermanager.clear"
  PermEnderchest: "easyservermanager.enderchest"
  PermFly: "easyservermanager.fly"
  PermAnnotherFly: "easyservermanager.fly.other"
  PermGameMode: "easyservermanager.gamemode"
  PermGameModeAnnotherPlayer: "easyservermanager.gamemode.other"
  PermGodModeAnnotherPlayer: "easyservermanager.god.other"
  PermGodMode: "easyservermanager.god"
  PermInvsee: "easyservermanager.invsee"
  PermJail: "easyservermanager.jail"
  PermHealAnnotherPlayer: "easyservermanager.heal.other"